5 get all articles
skelbon/news-api pull request #5
Opened 2023-10-03 15:37 UTC by skelbon

2023-10-03 16:03 UTC, Augs0 requested changes
Overall, looking pretty good but I'm unsure about your SQL query. Could you take a look at it?

2023-10-03 16:03 UTC, Augs0 commented on __tests__/app.test.js
> +describe('GET /api/articles/:article_id', ()=>{
This looks like code from a different endpoint

2023-10-03 16:03 UTC, Augs0 commented on __tests__/app.test.js
> +    test('should return status code 200', ()=>{
Nice testing !

2023-10-03 16:03 UTC, Augs0 commented on app.model.js
> +    return db.query(`SELECT CAST(COUNT(comments) AS INT) AS
Hey, not sure about this line. Can you explain what you're doing here? I'm pretty sure the count should be for comment_id and not the whole table

2023-10-04 07:56 UTC, skelbon commented on app.model.js
> +    return db.query(`SELECT CAST(COUNT(comments) AS INT) AS
Hi August. The query is good. The GROUP BY parameter ensures the count is applied to each grouping. It is then applied to the comment_count column.
[playground.txt](https://github.com/skelbon/news-api/files/12800835/playground.txt)

2023-10-04 07:59 UTC, merged